groups:
  - folder: Recording Rules
    name: SLI Recording Rules capacity
    interval: 1m
    rules:
      - uid: sli_node_exporter_5m
        title: sli_5m
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: avg_over_time((sum(1 - avg (rate(node_cpu_seconds_total{mode="idle"}[5m])) < bool 0.85)/count(1 - avg (rate(node_cpu_seconds_total{mode="idle"}[5m])) < bool 0.85))[5m:1m])
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
              refId: A
        labels:
          category: capacity
          app: node_exporter
        isPaused: false
        record:
          metric: sli_5m
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_node_exporter_window
        title: sli_window
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: sum without (sum_over_time((sli_5m{app="node_exporter"} < +Inf)[30d:5m])) / sum without (count_over_time((sli_5m{app="node_exporter"} < +Inf)[30d:5m]))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          category: capacity
          app: node_exporter
          grafana_slo_window: 30d
        isPaused: false
        record:
          metric: sli_window
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_node_exporter_info
        title: sli_info
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: vector(1)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          category: capacity
          grafana_slo_dashboard_url: https://dashingparrot1503.grafana.net/d/grafana_slo_app-node_exporter
          grafana_app: node_exporter
          grafana_slo_type: ratio
          app: node_exporter
        isPaused: false
        record:
          metric: sli_info
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_node_exporter_objective
        title: sli_objective
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: vector(0.999500)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          category: capacity
          app: node_exporter
          grafana_slo_window: 30d
        isPaused: false
        record:
          metric: sli_objective
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_node_exporter_ows
        title: sli_objective_window_seconds
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: vector(2592000)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          category: capacity
          app: node_exporter
          grafana_slo_window: 30d
        isPaused: false
        record:
          metric: sli_objective_window_seconds
          from: A
          targetDatasourceUid: prometheus