groups:
  - folder: Recording Rules
    name: SLI Recording Rules node-exporter
    interval: 1m
    rules:
      - uid: sli_ne_node_cpu_5m
        title: sli_node_cpu_5m
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                avg_over_time(
                  (
                    sum(1 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) < bool 0.85)
                    /
                    count(avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])))
                  )[5m:1m]
                )
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          sli: node_cpu
          category: capacity
          app: node-exporter
        isPaused: false
        record:
          metric: sli_5m
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_node_cpu_window
        title: sli_node_cpu_window
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                sum (sum_over_time((sli_5m{app="node-exporter", sli="node_cpu"} < +Inf)[30d:5m])) 
                / 
                sum (count_over_time((sli_5m{app="node-exporter", sli="node_cpu"} < +Inf)[30d:5m]))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          sli: node_cpu
          category: capacity
          app: node-exporter
          window: 30d
        isPaused: false
        record:
          metric: sli_window
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_node_memory_5m
        title: sli_node_memory_5m
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                avg_over_time(
                  (
                    sum(
                      (
                        1 - (
                          node_memory_MemAvailable_bytes{}  
                          /
                          node_memory_MemTotal_bytes{}  
                        )
                      ) < bool 0.90  
                    )
                    /
                    count(
                      node_memory_MemAvailable_bytes{}  
                      /
                      node_memory_MemTotal_bytes{}  
                    )
                  )[30m:5m]
                )
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          sli: node_memory
          category: capacity
          app: node-exporter
        isPaused: false
        record:
          metric: sli_5m
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_node_memory_window
        title: sli_node_memory_window
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                sum (sum_over_time((sli_5m{app="node-exporter", sli="node_memory"} < +Inf)[30d:5m])) 
                / 
                sum (count_over_time((sli_5m{app="node-exporter", sli="node_memory"} < +Inf)[30d:5m]))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          sli: node_memory
          category: capacity
          app: node-exporter
          window: 30d
        isPaused: false
        record:
          metric: sli_window
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_node_disk_5m
        title: sli_node_disk_5m
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                avg_over_time(
                    (
                        sum(
                            (
                                (
                                    rate(node_disk_read_time_seconds_total[1m])
                                    +
                                    rate(node_disk_write_time_seconds_total[1m])
                                )
                                /
                                (
                                    (
                                        rate(node_disk_reads_completed_total[1m])
                                        +
                                        rate(node_disk_writes_completed_total[1m])
                                    ) > 0
                                )
                            ) < bool 0.5
                        )
                        /
                        count(
                            (
                                rate(node_disk_reads_completed_total[1m])
                                +
                                rate(node_disk_writes_completed_total[1m])
                            ) > 0
                        )
                    )[5m:1m]
                )
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          sli: node_disk
          category: performance
          app: node-exporter
        isPaused: false
        record:
          metric: sli_5m
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_node_disk_window
        title: sli_node_disk_window
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                sum (sum_over_time((sli_5m{app="node-exporter", sli="node_disk"} < +Inf)[30d:5m])) 
                / 
                sum (count_over_time((sli_5m{app="node-exporter", sli="node_disk"} < +Inf)[30d:5m]))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          sli: node_disk
          category: performance
          app: node-exporter
          window: 30d
        isPaused: false
        record:
          metric: sli_window
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_probe_success_5m
        title: sli_probe_success_5m
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                avg_over_time(
                    (
                        sum(probe_success)
                        /
                        count(probe_success)
                    )[5m:1m]
                )
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          sli: probe_success
          category: availability
          app: node-exporter
        isPaused: false
        record:
          metric: sli_5m
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_probe_success_window
        title: sli_probe_success_window
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                sum (sum_over_time((sli_5m{app="node-exporter", sli="probe_success"} < +Inf)[30d:5m])) 
                / 
                sum (count_over_time((sli_5m{app="node-exporter", sli="probe_success"} < +Inf)[30d:5m]))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          sli: probe_success
          category: availability
          app: node-exporter
          window: 30d
        isPaused: false
        record:
          metric: sli_window
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_probe_duration_5m
        title: sli_probe_duration_5m
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                avg_over_time(
                    (
                        sum(probe_duration_seconds < bool 0.5)
                        /
                        count(probe_duration_seconds)
                    )[5m:1m]
                )
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          sli: probe_duration
          category: performance
          app: node-exporter
        isPaused: false
        record:
          metric: sli_5m
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_probe_duration_window
        title: sli_probe_duration_window
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                sum (sum_over_time((sli_5m{app="node-exporter", sli="probe_duration"} < +Inf)[30d:5m])) 
                / 
                sum (count_over_time((sli_5m{app="node-exporter", sli="probe_duration"} < +Inf)[30d:5m]))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          sli: probe_duration
          category: performance
          app: node-exporter
          window: 30d
        isPaused: false
        record:
          metric: sli_window
          from: A
          targetDatasourceUid: prometheus
          
      - uid: sli_ne_info
        title: sli_info
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: vector(1)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          dashboard_url: http://localhost:3000/d/slo-dashboard-node-exporter/slo-node-exporter?${__url_time_range}
          app: node-exporter
          window: 30d
        isPaused: false
        record:
          metric: sli_info
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_objective
        title: sli_objective
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: vector(0.9950)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          app: node-exporter
        isPaused: false
        record:
          metric: sli_objective
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_ne_ows
        title: sli_objective_window_seconds
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: vector(2592000)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          app: node-exporter
        isPaused: false
        record:
          metric: sli_objective_window_seconds
          from: A
          targetDatasourceUid: prometheus