name: monitoring_stack
services:
    logwriter:
        image: alpine:latest
        container_name: logwriter
        volumes:
            - ./services/logwriter/logwriter.sh:/logwriter.sh
            - ./logs:/var/log/logwriter
        command: sh -c 'chmod +x /logwriter.sh; /logwriter.sh'
        mem_limit: 32m
        cpus: 0.1
        restart: unless-stopped

    metricwriter:
        build:
            context: ./services/metricwriter
            dockerfile: Dockerfile
        image: metricwriter:latest
        container_name: metricwriter
        restart: unless-stopped
        environment:
            - PROMETHEUS_REMOTE_WRITE_URL=http://prometheus:9090/api/v1/write
            - POSTGRES_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-monitoring}?sslmode=disable

    mocktail:
        build:
            context: ./services/mocktail
            dockerfile: Dockerfile
        container_name: mocktail
        env_file:
            - ./services/mocktail/.env
        environment:
            - LOKI_URL=http://loki:3100
        ports:
            - "9095:9095"
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:9095/healthz",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
