name: monitoring_stack
services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - promdata:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.enable-remote-write-receiver"
            - "--web.enable-lifecycle"
        mem_limit: 256m
        cpus: 0.5
        ports:
            - "9090:9090"
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:9090/-/ready",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    promdata:
