name: monitoring_stack
services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - promdata:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.enable-remote-write-receiver"
            - "--web.enable-lifecycle"
        mem_limit: 256m
        cpus: 0.5
        ports:
            - "9090:9090"
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:9090/-/ready",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
            - "--path.rootfs=/rootfs"
            # Exclude unnecessary mounts to keep CPU/RAM usage extremely low
            - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
        mem_limit: 32m
        cpus: 0.1
        ports:
            - "9100:9100"
        restart: unless-stopped

    blackbox-exporter:
        image: prom/blackbox-exporter:latest
        container_name: blackbox-exporter
        mem_limit: 32m
        cpus: 0.1
        restart: unless-stopped
        ports:
            - "9115:9115"
        volumes:
            - ./configs/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro

volumes:
    promdata:
