{
 "title": "SLO node-exporter",
 "description": "A minimal example dashboard",
 "tags": [ "SLO" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "type": "text", "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 }, "options": { "content": "# node-exporter SLO\n" } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((count(GRAFANA_ALERTS{app=\"node-exporter\", grafana_slo_severity=\"critical\", alertstate=\"firing\"})) OR on() vector(0))",
     "legendFormat": "Critical alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((count(GRAFANA_ALERTS{app=\"node-exporter\", grafana_slo_severity=\"warning\", alertstate=\"firing\"})) OR on() vector(0))",
     "legendFormat": "Warning alert"
    }
   ]
  },
  {
   "title": "Time Window",
   "type": "stat",
   "description": "The time window over which the service level objective is being measured over",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sli_info{app=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "stat",
   "description": "The SLO's Objective value. Always between 0 and 100%",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sli_objective{app=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(avg by(app) (avg_over_time(sli_5m{app=\"node-exporter\"}[$__interval:])), 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sli_objective{app=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "30d SLI",
   "type": "stat",
   "description": "Service level indicator's value over the last 30d",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by(app) (sli_window{app=\"node-exporter\"}), 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sli_objective{app=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Trend",
   "type": "timeseries",
   "description": "If error budget is decreasing over time, it means that your service is spending its error budget faster than it's earning it back.\n\n If error budget is increasing overtime, you're not spending too much of your error budget.",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg by (app) (clamp_max(avg_over_time((sli_5m{app=\"node-exporter\"} < +Inf)[$__range:5m]), 1)) - on (app) sli_objective{app=\"node-exporter\"}) / (1 - sli_objective{app=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "30d Remaining Error Budget",
   "type": "stat",
   "description": "The unspent error budget over the last {0.9995 30d} Window",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(clamp_max(sli_window{app=\"node-exporter\"}, 1) - on (app) group_left () sli_objective{app=\"node-exporter\"}) / on (app) group_left () (1 - sli_objective{app=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Burn Rate",
   "type": "timeseries",
   "description": "The burn rate is the rate that this SLO is spending its error budget over last 5 min [0, 1.0]. A 1x burn rate will consume the entire error budget allotted for that period.",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (app) (1 - clamp_max(avg_over_time(sli_5m{app=\"node-exporter\"}[$__interval:]), 1)) / (1 - sli_objective{app=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Burn Rate",
   "type": "stat",
   "description": "The burn rate is the rate that this SLO is spending its error budget over last 5 min [0, 1.0]. A 1x burn rate will consume the entire error budget allotted for that period.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (app) (1 - clamp_max(avg_over_time(sli_5m{app=\"node-exporter\"}[$__interval:]), 1)) / (1 - sli_objective{app=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Burn Rate Alerts", "type": "alertlist", "description": "All active alerts for this SLO", "gridPos": { "h": 7, "w": 17, "x": 0, "y": 30 } },
  { "title": "Assistant Investigations", "type": "grafana-assistant-panel", "gridPos": { "h": 7, "w": 7, "x": 17, "y": 30 } }
 ]
}