{
 "title": "SLO Overview",
 "description": "SLO dashboard Overview",
 "tags": [ "SLO" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "⬆️ 1d target",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 1d",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (app) (sum_over_time((sli_success_count_5m < +Inf)[1d:5m]))\n\t\t  / sum by (app) (sum_over_time((sli_total_count_5m < +Inf)[1d:5m]))\n\t\t  # combine with series that aren't producing sli_success_count_5m and sli_total_count_5m\n\t\t  or avg by (app) (sli_1d)\n\t\t)\n\t\t> on(app) max by (app) (sli_objective)\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⬆️ 6h target",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 6h",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (app) (sum_over_time((sli_success_count_5m < +Inf)[6h:5m]))\n\t\t  / sum by (app) (sum_over_time((sli_total_count_5m < +Inf)[6h:5m]))\n\t\t  # combine with series that aren't producing sli_success_count_5m and sli_total_count_5m\n\t\t  or avg by (app) (sli_6h)\n\t\t)\n\t\t> on(app) max by (app) (sli_objective)\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⬆️ 1h target",
   "type": "stat",
   "description": "The number of SLIs that are meeting their SLO objective in the last 1h",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n\t\t(\n\t\t  sum by (app) (sum_over_time((sli_success_count_5m < +Inf)[1h:5m]))\n\t\t  / sum by (app) (sum_over_time((sli_total_count_5m < +Inf)[1h:5m]))\n\t\t  # combine with series that aren't producing sli_success_count_5m and sli_total_count_5m\n\t\t  or avg by (app) (sli_1h)\n\t\t)\n\t\t> on(app) max by (app) (sli_objective)\n\t  ) OR on() vector(0)\n\t  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO count",
   "type": "stat",
   "description": "The number of SLOs that are recording values",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (app)(sli_5m)) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI series",
   "type": "stat",
   "description": "The total number of series created by SLO recording rules.",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"sli_.*\", app!=\"\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "SLO name with hyperlink to the SLO's dashboard",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": {
    "content": "#### [backend](/d/slo-dashboard-backend/slo-backend?${__url_time_range})"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "30d SLI",
   "type": "stat",
   "description": "Service level indicator's value over the last 30d",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\nsum(sum_over_time((sli_success_count_5m{app=\"backend\"} < +Inf)[30d:5m]))\n/ sum(sum_over_time((sli_total_count_5m{app=\"backend\"} < +Inf)[30d:5m])), 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sli_objective{app=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Budget left",
   "type": "stat",
   "description": "The unspent error budget over the last {0.9995 30d} Window",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\tclamp_max(sum(sum_over_time((sli_success_count_5m{app=\"backend\"} < +Inf)[30d:5m]))\n\t\t/ sum(sum_over_time((sli_total_count_5m{app=\"backend\"} < +Inf)[30d:5m])), 1)\n\t\t- on() max by (app) (sli_objective{app=\"backend\"})\n\t)\n\t/ on () (1 - max by (app) (sli_objective{app=\"backend\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(sum(sum_over_time((sli_success_count_5m{app=\"backend\"} < +Inf)[$__interval:]))\n/ sum(sum_over_time((sli_total_count_5m{app=\"backend\"} < +Inf)[$__interval:])), 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sli_objective{app=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "SLO name with hyperlink to the SLO's dashboard",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": {
    "content": "#### [payment](/d/slo-dashboard-payment/slo-payment?${__url_time_range})"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "30d SLI",
   "type": "stat",
   "description": "Service level indicator's value over the last 30d",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\nsum(sum_over_time((sli_success_count_5m{app=\"payment\"} < +Inf)[30d:5m]))\n/ sum(sum_over_time((sli_total_count_5m{app=\"payment\"} < +Inf)[30d:5m])), 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sli_objective{app=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Budget left",
   "type": "stat",
   "description": "The unspent error budget over the last {0.9995 30d} Window",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\tclamp_max(sum(sum_over_time((sli_success_count_5m{app=\"payment\"} < +Inf)[30d:5m]))\n\t\t/ sum(sum_over_time((sli_total_count_5m{app=\"payment\"} < +Inf)[30d:5m])), 1)\n\t\t- on() max by (app) (sli_objective{app=\"payment\"})\n\t)\n\t/ on () (1 - max by (app) (sli_objective{app=\"payment\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(sum(sum_over_time((sli_success_count_5m{app=\"payment\"} < +Inf)[$__interval:]))\n/ sum(sum_over_time((sli_total_count_5m{app=\"payment\"} < +Inf)[$__interval:])), 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sli_objective{app=\"payment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "SLO name with hyperlink to the SLO's dashboard",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": {
    "content": "#### [node-exporter](/d/slo-dashboard-node-exporter/slo-node-exporter?${__url_time_range})"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "30d SLI",
   "type": "stat",
   "description": "Service level indicator's value over the last 30d",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by(app) (sli_window{app=\"node-exporter\"}), 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sli_objective{app=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Budget left",
   "type": "stat",
   "description": "The unspent error budget over the last {0.9995 30d} Window",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(clamp_max(sli_window{app=\"node-exporter\"}, 1) - on (app) group_left () sli_objective{app=\"node-exporter\"}) / on (app) group_left () (1 - sli_objective{app=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(avg by(app) (avg_over_time(sli_5m{app=\"node-exporter\"}[$__interval:])), 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sli_objective{app=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}