{
 "title": "SLO payment",
 "description": "SLO dashboard payment",
 "tags": [ "SLO" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "type": "text", "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 }, "options": { "content": "# payment SLO\n" } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((count(GRAFANA_ALERTS{slo_name=\"payment\", grafana_slo_severity=\"critical\", alertstate=\"firing\"})) OR on() vector(0))",
     "legendFormat": "Critical alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((count(GRAFANA_ALERTS{slo_name=\"payment\", grafana_slo_severity=\"warning\", alertstate=\"firing\"})) OR on() vector(0))",
     "legendFormat": "Warning alert"
    }
   ]
  },
  {
   "title": "Time Window",
   "type": "stat",
   "description": "The time window over which the service level objective is being measured over",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(vector(1), \"time_period\", \"30d\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "stat",
   "description": "The SLO's Objective value. Always between 0 and 100%",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0.9995)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "description": "Service level indicator",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_max(sum(sum_over_time((sli_success_count_5m{slo_name=\"payment\"} < +Inf)[$__interval:]))\n/ sum(sum_over_time((sli_total_count_5m{slo_name=\"payment\"} < +Inf)[$__interval:])), 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "((sum(rate(sli_logwriter_1m{service=\"payment\",status=\"success\"}[$__rate_interval] offset 2m)) or 0 * sum(rate(sli_logwriter_1m{service=\"payment\"}[$__rate_interval] offset 2m))) / sum(rate(sli_logwriter_1m{service=\"payment\"}[$__rate_interval] offset 2m))) AND timestamp(sum(rate(sli_logwriter_1m{service=\"payment\"}[$__rate_interval] offset 2m))) < 1782727587",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "30d SLI",
   "type": "stat",
   "description": "Service level indicator's value over the last 30d",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\nsum(sum_over_time((sli_success_count_5m{slo_name=\"payment\"} < +Inf)[30d:5m]))\n/ sum(sum_over_time((sli_total_count_5m{slo_name=\"payment\"} < +Inf)[30d:5m])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Burndown",
   "type": "timeseries",
   "description": "The error budget burndown in the selected time",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "300 * sum(sum_over_time((sli_total_count_5m{slo_name=\"payment\"} < +Inf)[$__range:5m] @ ${__to:date:seconds} offset 1s)) unless on() absent(sli_total_count_5m{slo_name=\"payment\"})",
     "legendFormat": "totalEvents"
    },
    {
     "expr": "clamp_min(300 * (sum(sum_over_time((sli_total_count_5m{slo_name=\"payment\"} < +Inf)[$__interval:5m] offset 1s)) \n- sum(sum_over_time((sli_success_count_5m{slo_name=\"payment\"} < +Inf)[$__interval:5m] offset 1s))), 0)",
     "legendFormat": "failureEventsInRange"
    }
   ]
  },
  {
   "title": "30d Remaining Error Budget",
   "type": "stat",
   "description": "The unspent error budget over the last {0.9995 30d} Window",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\tclamp_max(sum(sum_over_time((sli_success_count_5m{slo_name=\"payment\"} < +Inf)[30d:5m]))\n\t\t/ sum(sum_over_time((sli_total_count_5m{slo_name=\"payment\"} < +Inf)[30d:5m])), 1)\n\t\t- on() max by (slo_name) (sli_objective{slo_name=\"payment\"})\n\t)\n\t/ on () (1 - max by (slo_name) (sli_objective{slo_name=\"payment\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Burn Rate",
   "type": "timeseries",
   "description": "The burn rate is the rate that this SLO is spending its error budget over last 5 min [0, 1.0]. A 1x burn rate will consume the entire error budget allotted for that period.",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n\t\t1 - clamp_max((sum(sum_over_time((sli_success_count_5m{slo_name=\"payment\"} < +Inf)[$__interval:]))\n\t\t/ sum(sum_over_time((sli_total_count_5m{slo_name=\"payment\"} < +Inf)[$__interval:]))), 1)\n)\n/ on() (1 - max by (slo_name) (sli_objective{slo_name=\"payment\"}))\n# omit NaN by comparing to Infinity\n< 1e+308",
     "legendFormat": "__auto"
    },
    {
     "expr": "((1 - ((sum(rate(sli_logwriter_1m{service=\"payment\",status=\"success\"}[$__rate_interval] offset 2m)) or 0 * sum(rate(sli_logwriter_1m{service=\"payment\"}[$__rate_interval] offset 2m))) / sum(rate(sli_logwriter_1m{service=\"payment\"}[$__rate_interval] offset 2m)))) / (1 - 0.9995)) AND timestamp(sum(rate(sli_logwriter_1m{service=\"payment\"}[$__rate_interval] offset 2m))) < 1782727587",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Burn Rate",
   "type": "stat",
   "description": "The burn rate is the rate that this SLO is spending its error budget over last 5 min [0, 1.0]. A 1x burn rate will consume the entire error budget allotted for that period.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\t\t1 - clamp_max((sum(sum_over_time((sli_success_count_5m{slo_name=\"payment\"} < +Inf)[$__interval:]))\n\t\t/ sum(sum_over_time((sli_total_count_5m{slo_name=\"payment\"} < +Inf)[$__interval:]))), 1)\n)\n/ on() (1 - max by (slo_name) (sli_objective{slo_name=\"payment\"}))\n# omit NaN by comparing to Infinity\n< 1e+308",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Burn Rate Alerts", "type": "alertlist", "description": "All active alerts for this SLO", "gridPos": { "h": 7, "w": 17, "x": 0, "y": 30 } },
  { "title": "Assistant Investigations", "type": "grafana-assistant-panel", "gridPos": { "h": 7, "w": 7, "x": 17, "y": 30 } },
  {
   "title": "Event Rate",
   "type": "timeseries",
   "description": "Total Rate (for SLIs that compare rate of successful events to rate of total events, this is the latter)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (slo_name) (avg_over_time(sli_total_count_5m{slo_name=\"payment\"}[$__interval:]))"
    },
    {
     "expr": "(sum(rate(sli_logwriter_1m{service=\"payment\"}[$__rate_interval] offset 2m))) AND timestamp(sum(rate(sli_logwriter_1m{service=\"payment\"}[$__rate_interval] offset 2m))) < 1782727587"
    }
   ]
  }
 ]
}