groups:
  - folder: Recording Rules
    name: SLI Recording Rules payment
    interval: 1m
    rules:
      - uid: sli_payment_sc_5m
        title: sli_success_count_5m
        condition: ""
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              expr: 'sum(metricwriter{service="payment", status="success"}) or 0 * sum(metricwriter{service="payment"})'
              instant: true
              refId: A
        labels:
          category: availability
          app: payment
        noDataState: OK
        execErrState: Error
        isPaused: false
        record:
          metric: sli_success_count_5m
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_payment_tc_5m
        title: sli_total_count_5m
        condition: ""
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              expr: 'sum(metricwriter{service="payment"})'
              instant: true
              refId: A
        labels:
          category: availability
          app: payment
        noDataState: OK
        execErrState: Error
        isPaused: false
        record:
          metric: sli_total_count_5m
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_payment_5m
        title: sli_5m
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: (sum(sum_over_time(metricwriter{service="payment",status="success"}[5m] offset 2m)) or 0 * sum(sum_over_time(metricwriter{service="payment"}[5m] offset 2m))) / sum(sum_over_time(metricwriter{service="payment"}[5m] offset 2m))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          category: availability
          app: payment
        isPaused: false
        record:
          metric: sli_5m
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_payment_30m
        title: sli_30m
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: (sum(rate(metricwriter{service="payment",status="success"}[30m] offset 2m)) or 0 * sum(rate(metricwriter{service="payment"}[30m] offset 2m))) / sum(rate(metricwriter{service="payment"}[30m] offset 2m))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          category: availability
          app: payment
        isPaused: false
        record:
          metric: sli_30m
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_payment_7d
        title: sli_7d
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                (sum_over_time((sli_success_count_5m{app="payment"} < +Inf)[7d:5m])) 
                / 
                (sum_over_time((sli_total_count_5m{app="payment"} < +Inf)[7d:5m]))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          category: availability
          app: payment
        isPaused: false
        record:
          metric: sli_3d
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_payment_window
        title: sli_window
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: |
                (sum_over_time((sli_success_count_5m{app="payment"} < +Inf)[30d:5m])) 
                / 
                (sum_over_time((sli_total_count_5m{app="payment"} < +Inf)[30d:5m]))
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          category: availability
          app: payment
          window: 30d
        isPaused: false
        record:
          metric: sli_window
          from: A
          targetDatasourceUid: prometheus

      - uid: sli_payment_info
        title: sli_info
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: vector(1)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          dashboard_url: http://localhost:3000/d/slo-dashboard-payment/slo-payment?${__url_time_range}
          app: payment
        isPaused: false
        record:
          metric: sli_info
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_payment_objective
        title: sli_objective
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: vector(0.999500)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          app: payment
        isPaused: false
        record:
          metric: sli_objective
          from: A
          targetDatasourceUid: prometheus
      - uid: sli_payment_ows
        title: sli_objective_window_seconds
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                dstype: prometheus
                uid: prometheus
              expr: vector(2592000)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
        labels:
          app: payment
        isPaused: false
        record:
          metric: sli_objective_window_seconds
          from: A
          targetDatasourceUid: prometheus