package metrics

import (
	"fmt"
	"math/rand"
	"sync"
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

var (
	mu sync.RWMutex

	logCounter = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "mocktail_logs_total",
			Help: "Total number of logs generated by mocktail",
		},
		[]string{"level", "status", "service"},
	)

	requestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "mocktail_request_duration_seconds",
			Help:    "Request duration for mocktail endpoints",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"path", "method"},
	)

	// customGauges stores dynamically-created gauge metrics by name
	customGauges = make(map[string]*prometheus.GaugeVec)
	// customCounters stores dynamically-created counter metrics by name
	customCounters = make(map[string]*prometheus.CounterVec)
	// activeMetrics tracks metrics that are actively updating in background
	activeMetrics = make(map[string]bool)
	// stopChannels stores channels to stop background goroutines
	stopChannels = make(map[string]chan struct{})
	randSrc        = rand.New(rand.NewSource(time.Now().UnixNano()))
)

func RegisterMetrics() {
	if err := prometheus.Register(logCounter); err != nil {
		if are, ok := err.(prometheus.AlreadyRegisteredError); ok {
			logCounter = are.ExistingCollector.(*prometheus.CounterVec)
		}
	}
	if err := prometheus.Register(requestDuration); err != nil {
		if are, ok := err.(prometheus.AlreadyRegisteredError); ok {
			requestDuration = are.ExistingCollector.(*prometheus.HistogramVec)
		}
	}
}

func RecordLog(level, status, service string) {
	logCounter.WithLabelValues(level, status, service).Inc()
}

func RecordRequest(method, path string, duration float64) {
	requestDuration.WithLabelValues(path, method).Observe(duration)
}

// RegisterCustomGauge creates a new Prometheus GaugeVec with the given name and labels
func RegisterCustomGauge(name string, labelNames []string) error {
	mu.Lock()
	defer mu.Unlock()

	if _, exists := customGauges[name]; exists {
		return nil
	}
	if _, exists := customCounters[name]; exists {
		return fmt.Errorf("metric %s already registered as counter", name)
	}

	sanitizedName := sanitizeMetricName(name)

	gauge := prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: sanitizedName,
			Help: "Custom metric from Mocktail UI",
		},
		labelNames,
	)

	if err := prometheus.Register(gauge); err != nil {
		if are, ok := err.(prometheus.AlreadyRegisteredError); ok {
			customGauges[name] = are.ExistingCollector.(*prometheus.GaugeVec)
		} else {
			return err
		}
	} else {
		customGauges[name] = gauge
	}

	return nil
}

// RegisterCustomCounter creates a new Prometheus CounterVec with the given name and labels
func RegisterCustomCounter(name string, labelNames []string) error {
	mu.Lock()
	defer mu.Unlock()

	if _, exists := customCounters[name]; exists {
		return nil
	}
	if _, exists := customGauges[name]; exists {
		return fmt.Errorf("metric %s already registered as gauge", name)
	}

	sanitizedName := sanitizeMetricName(name)

	counter := prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: sanitizedName,
			Help: "Custom metric from Mocktail UI",
		},
		labelNames,
	)

	if err := prometheus.Register(counter); err != nil {
		if are, ok := err.(prometheus.AlreadyRegisteredError); ok {
			customCounters[name] = are.ExistingCollector.(*prometheus.CounterVec)
		} else {
			return err
		}
	} else {
		customCounters[name] = counter
	}

	return nil
}

// RegisterCustomMetric registers either a gauge or counter based on type
func RegisterCustomMetric(name, metricType string, labelNames []string) error {
	if metricType == "counter" {
		return RegisterCustomCounter(name, labelNames)
	}
	return RegisterCustomGauge(name, labelNames)
}

// SetCustomGauge sets a value on a registered gauge metric
func SetCustomGauge(name string, labels map[string]string, value float64) error {
	mu.RLock()
	gauge, exists := customGauges[name]
	mu.RUnlock()

	if !exists {
		return fmt.Errorf("gauge metric %s not registered", name)
	}

	gauge.With(labels).Set(value)
	return nil
}

// SetCustomCounter increments a counter metric
func SetCustomCounter(name string, labels map[string]string, value float64) error {
	mu.RLock()
	counter, exists := customCounters[name]
	mu.RUnlock()

	if !exists {
		return fmt.Errorf("counter metric %s not registered", name)
	}

	counter.With(labels).Add(value)
	return nil
}

// SetCustomMetric sets a value on a registered metric
func SetCustomMetric(name, metricType string, labels map[string]string, value float64) error {
	if metricType == "counter" {
		return SetCustomCounter(name, labels, value)
	}
	return SetCustomGauge(name, labels, value)
}

// StartBackgroundUpdater starts a goroutine that updates a metric with randomized values
// For gauges: randomizes between min and max values
// For counters: increments by the specified increment value at the interval
func StartBackgroundUpdater(name, metricType string, labels map[string]string, minValue, maxValue, increment float64, intervalSec int) {
	mu.Lock()
	// Stop any existing goroutine for this metric
	if ch, exists := stopChannels[name]; exists {
		close(ch)
		delete(stopChannels, name)
	}

	ch := make(chan struct{})
	stopChannels[name] = ch
	activeMetrics[name] = true
	mu.Unlock()

	go func() {
		ticker := time.NewTicker(time.Duration(intervalSec) * time.Second)
		defer ticker.Stop()

		// Set initial value
		if metricType == "counter" {
			_ = SetCustomCounter(name, labels, increment)
		} else {
			randomValue := minValue + rand.New(randSrc).Float64()*(maxValue-minValue)
			_ = SetCustomGauge(name, labels, randomValue)
		}

		for {
			select {
			case <-ch:
				mu.Lock()
				delete(activeMetrics, name)
				mu.Unlock()
				return
			case <-ticker.C:
				if metricType == "counter" {
					_ = SetCustomCounter(name, labels, increment)
				} else {
					randomValue := minValue + rand.New(randSrc).Float64()*(maxValue-minValue)
					_ = SetCustomGauge(name, labels, randomValue)
				}
			}
		}
	}()
}

// StopBackgroundUpdater stops the background update goroutine for a metric
func StopBackgroundUpdater(name string) {
	mu.Lock()
	defer mu.Unlock()

	if ch, exists := stopChannels[name]; exists {
		close(ch)
		delete(stopChannels, name)
	}
	delete(activeMetrics, name)
}

// sanitizeMetricName ensures the metric name follows Prometheus naming conventions
func sanitizeMetricName(name string) string {
	var result []rune
	for i, r := range name {
		if i == 0 && !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_') {
			result = append(result, '_')
		} else if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == ':') {
			result = append(result, '_')
		} else {
			result = append(result, r)
		}
	}
	return string(result)
}
